### ISSUE TITLE
AAAS(AutoAPI As A Service)

### ISSUE THREAD

**Issue by longfangsong** [SHUReeducation/autoAPI#15]
Write a web service to call this remotely and deploy it to somewhere.

**Comment by zhoudian64** [comment]
I think we should separate `call` and `deploy` into two issues. Then sum them up.

**Comment by longfangsong** [comment]
> I think we should separate `call` and `deploy` into two issues. Then sum them up.

实际上我也有考虑直接上 wasm 把它直接port到前端然后省去 deploy 的步骤
