### ISSUE TITLE
Java Backend Support

### ISSUE THREAD

**Issue by ferryvan** [SHUReeducation/autoAPI#22]
**Describe the solution you'd like**
WE NEED JAVA!

**Additional context**
#JAVA LIVES MATTER

**Comment by longfangsong** [comment]
# NO
JAVA LIVES DOESN'T MATTER
I'LL SPEND ALL MY LIFE TO KILL JAVA!!!
THIS IS A MATTER OF PRICIPLE, ANYONE WHO THINK JAVA IS GOOD, PLEASE GET OUT OF THIS REPO AT ONCE!!!

**Comment by zhoudian64** [comment]
I gonna add a bot see if there are other silly java guys.
