### ISSUE TITLE
CLI flags

### ISSUE THREAD

**Issue by zhoudian64** [SHUReeducation/autoAPI#31]
Maybe we need a `--force` flag for our cli tool to control if `rm -rf output` before generate.
And a `-h / --help` for displaying usage.

**Comment by longfangsong** [comment]
> And a `-h / --help` for displaying usage.

这个东西 urfave/cli/v2 好像自带了

**Comment by zhoudian64** [comment]
I means if `output` dir exist, we should not generate and tell user to add `--force` flag.
check [here](https://github.com/SHUReeducation/autoAPI/blob/e4d3efca32c834a91483ba60c9f1f9bcc23142a1/generator/apiGenerator/golang/apiGenerator.go#L99)
