### ISSUE TITLE
提供一种 fill yaml 中空值为默认值的方案

### ISSUE THREAD

**Issue by longfangsong** [SHUReeducation/autoAPI#33]
**Describe the solution you'd like**

暂定：
为所有可能为空值的field实现 unmarshaler，并提供为空时的处理函数

**Comment by zhoudian64** [comment]
Just use string.

**Comment by longfangsong** [comment]
> Just use string.

这主意太糟了。
况且这也没解决填入默认值的问题。
（说到底是Go大便，没有`Option`、`Either`之类的好货）
