### ISSUE TITLE
文件末尾自动添加换行

### ISSUE THREAD

**Issue by zhoudian64** [SHUReeducation/autoAPI#58]
**Describe the solution you'd like**
所有文件是否需要统一，最后需要一行换行。

**Additional context**
Github review时能看到非常多的最后没有换行。

**Comment by longfangsong** [comment]
> **Describe the solution you'd like**
> 所有文件是否需要统一，最后需要一行换行。
> 
> **Additional context**
> Github review时能看到非常多的最后没有换行。

实际上我个人是不太在意这个事情的。

不过业界都希望有换行来着。

我建议写(chao)个脚本自动给我们加上换行，然后加到 `git hooks` 里面每次commit前自动跑。

**Comment by laojianzi** [comment]
如果为了代码和 review 更好的阅读，建议可以考虑添加一些 .editconfig、golangci-lint 等工具来辅助

**Comment by longfangsong** [comment]
Replaced by #78.
