### ISSUE TITLE
Linting support

### ISSUE THREAD

**Issue by longfangsong** [SHUReeducation/autoAPI#78]
**Describe the solution you'd like**

As @laojianzi [suggested](https://github.com/SHUReeducation/autoAPI/issues/58#issuecomment-685290634)，引入一个linting tool。

**Additional context**
不知道会不会提高开发者的门槛……希望不会吧

**Comment by laojianzi** [comment]
会对不习惯的开发者带来一定的困扰，但挺有用的，提升代码质量很直接的一个方式，可以考虑使用建议但不强制的方式

另外 `goimport` 格式化也可以考虑安排上，为什么不用 `gofmt`？因为 `goimport` 可以 sort import，这个倒是没有门槛
